//
// Created by juanpr on 13/6/21.
//

#ifndef ITCR_DATOSII_PROYECTOII_LETSPLAY_SERVER_STARNODE_H
#define ITCR_DATOSII_PROYECTOII_LETSPLAY_SERVER_STARNODE_H


class StarNode {

};


#endif //ITCR_DATOSII_PROYECTOII_LETSPLAY_SERVER_STARNODE_H
